CREATE DATABASE IF NOT EXISTS empleados;
USE empleados;

CREATE USER IF NOT EXISTS emple IDENTIFIED BY 'emple';
GRANT ALL PRIVILEGES ON empleados.* TO emple;

FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS tcentr
(
numce INTEGER PRIMARY KEY,
nomce VARCHAR(30) NOT NULL,
direccion VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS tdepto
(
numde INTEGER PRIMARY KEY,
numce INTEGER NOT NULL,
direc INTEGER NOT NULL,
tidir ENUM('P', 'F') NOT NULL,
presu DECIMAL(10,2) NOT NULL,
depde INTEGER,
nomde VARCHAR(50) NOT NULL,
CONSTRAINT fk_tdepto_tcentr
FOREIGN KEY (numce)
REFERENCES tcentr(numce)
);

CREATE TABLE IF NOT EXISTS temple
(
numem INTEGER PRIMARY KEY,
numde INTEGER NOT NULL,
extel INTEGER  NOT NULL,
fecna DATE NOT NULL,
fecin DATE NOT NULL,
salar DECIMAL(10,2) NOT NULL,
comis DECIMAL(10,2),
numhi INTEGER NOT NULL,
nomem VARCHAR(50),
CONSTRAINT fk_temple_tdepto
FOREIGN KEY (numde)
REFERENCES tdepto(numde)
);
